USE communityThrive2DB
GO


GO


GO

CREATE TABLE ct2Inventory(
	inventoryID INT IDENTITY(1,1) NOT NULL,
	donationID INT NULL,
	quantity INT NULL,
	[description] VARCHAR(255) NULL,
	categoryID INT NULL

PRIMARY KEY CLUSTERED 
(
	inventoryID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


