USE communityThrive2DB
GO


GO


GO

CREATE TABLE ct2Privileges(
	privilegesID INT IDENTITY(1,1) NOT NULL,
	privilegesDescription NVARCHAR(150) NULL,
PRIMARY KEY CLUSTERED 
(
	privilegesID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


