USE communityThrive2DB
GO


GO


GO

CREATE TABLE ct2Role(
	roleID INT IDENTITY(1,1) NOT NULL,
	roleDescription NVARCHAR(150) NULL
	
	
PRIMARY KEY CLUSTERED 
(
	roleID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


