USE communityThrive2DB
GO


GO


GO

CREATE TABLE ct2RolePrivileges(
	roleFK INT IDENTITY(1,1) NULL,
	privilegeFK INT NULL
	
	
PRIMARY KEY CLUSTERED 
(
	roleFK ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


