USE communityThrive2DB
GO


GO


GO

CREATE TABLE ct2User(
	userID INT IDENTITY(1,1) NOT NULL,
	roleID INT NOT NULL,
	companyID INT NULL,
	emailAddress NVARCHAR(150)NOT NULL,
	userPassword NVARCHAR(150) NOT NULL,
	firstName NVARCHAR(100) NOT NULL,
	lastName NVARCHAR(100) NOT NULL,
	phoneNumber NVARCHAR(100) NULL,
	userAddress NVARCHAR(200) NULL,
	userTypeID INT NULL
	
PRIMARY KEY CLUSTERED 
(
	userID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


